config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: "homes#top"
    resources :customers,     only: [:index, :show, :edit, :update]
    resources :post_comments, only: [:index, :destroy]
  end


  scope module: 'public' do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources :recipes, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:new, :create, :destroy]
      collection do
        get 'search', as: 'recipe_search'
      end
    end
    resource :customer, only: [:show, :edit, :update] do
      member do
        get 'favorites'
      end
      get 'information/edit' => "customers#edit", on: :collection
      get 'leave',        on: :collection
      patch 'withdwaral', on: :collection
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :favorites,     dependent: :destroy
  has_many :favorited_recipes, through: :favorites, source: :recipe
  has_many :post_comments, dependent: :destroy
         
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customer = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      @customer = Customer.find(params[:id])
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container ">
  <div class="row m-4">
    <div class="col-12" style="font-size:70px;color:#EEEEEE;">EDIT</div>
    <div class="col-12" style="font-size:25px;">
      <%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集
    </div>

    <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
    <table class="row m-5">
      <tr>
        <th class="py-2 col-3">名前</th>
        <td><%= f.text_field :last_name %> <%= f.text_field :first_name %></td>
      </tr>
      <tr>
        <th class="py-2 col-3">メールアドレス</th>
        <td class="py-2 col-6"><%= f.text_field :email, class: "col-9" %></td>
      </tr>
      <tr>
        <th class="py-2 col-3">会員ステータス</th>
        <td class="py-2 col-6">
          <%= f.radio_button :is_deleted, false %><%= f.label :is_deleted,'有効', value: false %> 
          <%= f.radio_button :is_deleted, true %><%= f.label :is_deleted,'無効', value: true %>
        </td>
      </tr>
      <tr>
        <td>
          <%= button_tag type: "submit", class: "btn btn-outline-secondary nav-link mt-5 py-2 col-6", style: 'color: black;width:120px;' do %>
            <i class="fa-solid fa-rotate-right" style="color: #000000;">更新する</i>
          <% end %>
        </td>
      </tr>
    </table>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container ">
  <div class="row m-4">
    <div class="col-12" style="font-size:70px;color:#EEEEEE;">USER</div>
    <div class="col-12" style="font-size:25px;">会員一覧</div>
  </div>
  
  <div class="row m-5">
    <table class="table">
      <thead class="bg-light">
        <tr>
          <th>会員ID</th>
          <th>名前</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customer.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to "#{customer.last_name}#{customer.first_name}", admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td>
          <% if customer.is_deleted == false %>
            <td class="text-success">有効</td>
          <% else %>
            <td class="text-black-50">退会</td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="d-flex justify-content-center text-center my-5">
      <%= paginate @customer %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container ">
  <div class="row m-4">
    <div class="col-12" style="font-size:70px;color:#EEEEEE;">SHOW</div>
    <div class="col-12" style="font-size:25px;">
      <%= @customer.last_name %><%= @customer.first_name %>さんの会員情報詳細
    </div>
  </div>
  
  <div class="row m-5">
    <table class="table">
      <tr>
        <th class="pl-5 bg-light text-dark" style="width:300px;">名前</th>
        <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
      </tr>
      <tr>
        <th class="pl-5 bg-light text-dark">メールアドレス</th>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <th class="pl-5 bg-light text-dark">会員ステータス</th>
        <% if @customer.is_deleted == false %>
          <td class="text-success">有効</td>
        <% else %>
          <td class="text-black-50">退会</td>
        <% end %>
      </tr>
    </table>
  </div>
    
  <div class="col-2 m-5">
    <div type="button" class="btn btn-outline-secondary nav-link">
      <%= link_to "編集する", edit_admin_customer_path(@customer), class: 'nav-link fa-solid fa-pen', style: 'color: black;'%>
    </div>
  </div>
</div>