config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: "homes#top"
    resources :customers,     only: [:index, :show, :edit, :update]
    resources :post_comments, only: [:index, :destroy]
  end


  scope module: 'public' do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources :recipes, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:new, :create, :destroy]
      collection do
        get 'search', as: 'recipe_search'
      end
    end
    resource :customer, only: [:show, :edit, :update] do
      member do
        get 'favorites'
      end
      get 'information/edit' => "customers#edit", on: :collection
      get 'leave',        on: :collection
      patch 'withdwaral', on: :collection
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
  
  validates :comment, presence: true
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  def index
    @post_comments = PostComment.page(params[:page]).per(10)
  end
  
  def destroy
    @post_comment = PostComment.find(params[:id])
    @post_comment.destroy
    redirect_to admin_post_comments_path
  end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/index.html.erb
<div class="container ">
  <div class="row m-4">
    <div class="col-12" style="font-size:70px;color:#EEEEEE;">COMMENTS</div>
    <div class="col-12" style="font-size:25px;">コメント一覧</div>
  </div>
  <table class="table my-5">
    <thead class="bg-light">
      <tr>
        <th>会員名</th>
        <th style="width:120px;">レシピ名</th>
        <th style="width:280px;"></th>
        <th style="width:520px;">コメント内容</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @post_comments.each do |post_comment| %>
        <tr>
          <td><%= post_comment.customer.last_name %><%= post_comment.customer.first_name %></td>
          <td><% if post_comment.recipe.image.present? %>
                <%= image_tag post_comment.recipe.image, width: 100, height: 70, class: "img-resize, rounded mx-auto d-block" %>
              <% else %>
                <%= image_tag "no_image.jpg", width: 100, height: 70, class: "img-resize, rounded mx-auto d-block" %>
              <% end %></td>
          <td><%= post_comment.recipe.name %></td>
          <td><%= post_comment.comment %></td>
          <td><%= button_to "削除", recipe_post_comment_path(post_comment.recipe, post_comment), method: :delete, class: "btn btn-outline-secondary nav-link py-1", style: 'color: black; width: 70px;', form: { class: "d-inline" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center text-center mt-5 mb-5">
    <%= paginate @post_comments %>
  </div>
</div>