config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: "homes#top"
    resources :customers,     only: [:index, :show, :edit, :update]
    resources :post_comments, only: [:index, :destroy]
  end


  scope module: 'public' do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources :recipes, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:new, :create, :destroy]
      collection do
        get 'search', as: 'recipe_search'
      end
    end
    resource :customer, only: [:show, :edit, :update] do
      member do
        get 'favorites'
      end
      get 'information/edit' => "customers#edit", on: :collection
      get 'leave',        on: :collection
      patch 'withdwaral', on: :collection
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :favorites,     dependent: :destroy
  has_many :favorited_recipes, through: :favorites, source: :recipe
  has_many :post_comments, dependent: :destroy
         
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
  
  validates :comment, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one_attached :image
  has_many :favorites,      dependent: :destroy
  has_many :favorited_customers, through: :favorites, source: :customer
  has_many :post_comments,  dependent: :destroy
  has_many :recipe_tags,    dependent: :destroy
  has_many :tags,           through: :recipe_tags
  
  validates :name,     presence: true
  validates :time,     presence: true
  validates :material, presence: true
  validates :make,     presence: true
  validates :tag_ids,  presence: true
  
  def favorited_by?(customer)
    if customer.present?
      favorites.where(customer_id: customer.id).exists?
    else
      false
    end
  end
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :recipe_tags, dependent: :destroy
  has_many :recipes, through: :recipe_tags
  
  validates :name,     presence: true
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customer = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      @customer = Customer.find(params[:id])
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :email, :is_deleted)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  def index
    @post_comments = PostComment.page(params[:page]).per(10)
  end
  
  def destroy
    @post_comment = PostComment.find(params[:id])
    @post_comment.destroy
    redirect_to admin_post_comments_path
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  
    def after_sign_in_path_for(resource)
      admin_root_path
    end
  
    def after_sign_out_path_for(resource)
      new_admin_session_path
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url
  
  def admin_url
    request.fullpath.include?("/admin")
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<!--管理者はサインインの機能のみが存在-->
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-light" style="height:120px;">
  
</footer>

app/views/layouts/_header.html.erb
<% if admin_signed_in? %>
  <% if request.fullpath.include? "/admin" %>
  <!--adminのheader-->
    <header class="header">
      <nav class="navbar navbar-expand-lg" >
          <div class="container-fluid" >
            <a href="/admin" >
              <%= image_tag("logo1.png", size: "160x50") %>
            </a>
            
            <div>
              <p style="font-size:40px;">Hello!</p>
            </div>

          <div>
            <ul class="navbar-nav ml-auto m-2 d-flex">
              <li class="nav-item ml-3">
                <%= link_to "会員一覧", "/admin/customers", class: 'nav-link', style: 'color: black;' %>
              </li>
              <li class="nav-item ml-3">
                <%= link_to "コメント一覧", "/admin/post_comments", class: 'nav-link', style: 'color: black;' %>
              </li>
              <li class="nav-item ml-3 mt-1">
                <%= button_to destroy_admin_session_path, method: :delete, class: 'btn d-flex align-items-center', style: 'color: black; border-color:white;' do %>
                  <i class="fa-solid fa-right-from-bracket" style="color: #000000;"></i>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% else %>
    <!--customerのheaderを返す -->
      <header class="header">
        <nav class="navbar navbar-expand-lg" >
          <div class="container-fluid" >
            <a href="/" >
              <%= image_tag("logo1.png", size: "160x50") %>
            </a>

            <div>
              <ul class="navbar-nav ml-auto m-2 d-flex">
                <li class="nav-item ml-3">
                  <%= link_to "Top", "/", class: 'nav-link', style: 'color: black;' %>
                </li>
                <li class="nav-item ml-3">
                  <%= link_to "Cook Shareとは", "/about", class: 'nav-link', style: 'color: black;' %>
                </li>
                <li class="nav-item ml-3">
                  <%= link_to "レシピ一覧", "/recipes", class: 'nav-link', style: 'color: black;' %>
                </li>
                <li class="nav-item ml-3">
                  <a class="fa-solid fa-user pt-2 px-2 nav-link" style="color: black;" href="/customer"></a>
                </li>
                <li class="nav-item ml-3">
                  <a class="fa-solid fa-heart pt-2 px-2 nav-link" style="color: black;" href="/customer/favorites"></a>
                </li>
                <li class="nav-item ml-3">
                  <%= button_to destroy_customer_session_path, method: :delete, class: 'btn d-flex align-items-center', style: 'color: black; border-color:white;' do %>
                    <i class="fa-solid fa-right-from-bracket" style="color: #000000;"></i>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <% end %>
    <% elsif customer_signed_in? %>
    <!--customerがログインしているとき-->
      <header class="header">
        <nav class="navbar navbar-expand-lg" >
          <div class="container-fluid" >
            <a href="/" >
              <%= image_tag("logo1.png", size: "160x50") %>
            </a>
            
            <div class="mt-4">
              <p>ようこそ、<%= current_customer.last_name %>さん！</p>
            </div>

            <div>
              <ul class="navbar-nav ml-auto m-2 d-flex">
                <li class="nav-item ml-3">
                  <%= link_to "Top", "/", class: 'nav-link', style: 'color: black;' %>
                </li>
                <li class="nav-item ml-3">
                  <%= link_to "Cook Shareとは", "/about", class: 'nav-link', style: 'color: black;' %>
                </li>
                <li class="nav-item ml-3">
                  <%= link_to "レシピ一覧", "/recipes", class: 'nav-link', style: 'color: black;' %>
                </li>
                <li class="nav-item ml-3">
                  <a class="fa-solid fa-user pt-2 px-2 nav-link" style="color: black;" href="/customer"></a>
                </li>
                <li class="nav-item ml-3">
                  <a class="fa-solid fa-heart pt-2 px-2 nav-link" style="color: black;" href="/customer/favorites"></a>
                </li>
                <li class="nav-item ml-3">
                  <%= button_to destroy_customer_session_path, method: :delete, class: 'btn d-flex align-items-center', style: 'color: black; border-color:white;' do %>
                    <i class="fa-solid fa-right-from-bracket" style="color: #000000;"></i>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    <% else %>
    <!-- customerがログインしていない時-->
      <header class="header">
        <nav class="navbar navbar-expand-lg" >
          <div class="container-fluid" >
            <a href="/" >
              <%= image_tag("logo1.png", size: "160x50") %>
            </a>

            <div>
              <ul class="navbar-nav ml-auto m-2">
                <li class="nav-item ml-3">
                  <%= link_to "Top", "/", class: 'nav-link', style: 'color: black;' %>
                </li>
                <li class="nav-item ml-3">
                  <%= link_to "Cook Shareとは", "/about", class: 'nav-link', style: 'color: black;' %>
                </li>
                <li class="nav-item ml-3">
                  <%= link_to "レシピ一覧", "/recipes", class: 'nav-link', style: 'color: black;' %>
                </li>
                <li class="nav-item ml-3">
                  <a class="fa-solid fa-user-plus pt-2 px-2 nav-link" style="color: black;" href="/customers/sign_up"></a>
                </li>
                <li class="nav-item ml-3">
                  <a class="fa-solid fa-right-to-bracket pt-2 px-2 nav-link" style="color: black;" href= "/customers/sign_in"></a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookShare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e3ef32b632.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="body-content">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>

    <% if flash.any? %>
      <script type="text/javascript">
        <% flash.each do |key, value| %>
          <% key = "success" if key == "notice" %>
          <% key = "error" if key == "alret" %> <!-- Change "alret" to "error" -->
          toastr['<%= key %>']('<%= value %>');
        <% end %>
      </script>
    <% end %>
  </body>
</html>